# Directory to parse
source: patterns

# Directory to build the styleguide
destination: ../build

# Hologram theme
documentation_assets: bower_components/Cortana
custom_markdown: bower_components/Cortana/CortanaMarkdownRenderer.rb

# To have a custom index page build with your README.md
index: README

# A list of relative paths to folders containing any dependencies to copy
dependencies:
  - assets
  - vendor_assets
  - prototypes

# List all css to include for the styleguide render examples (path from styleguide directory)
css_include:
  - 'assets/css/patterns.css'
  - 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'
  - 'vendor_assets/slick/slick.css'
  - 'vendor_assets/slick/slick-theme.css'


# List all js to include for the styleguide render examples (path from styleguide directory)
js_include:
  - 'vendor_assets/js/jquery.min.js'
  - 'vendor_assets/bootstrap.6-dist/js/bootstrap.min.js'
  - 'vendor_assets/slick/slick.min.js'

# String who is used to split the category name and create category wrapper
name_scope: '-'

# To output navigation for top level sections, set the value to
# 'section'. To output navigation for sub-sections, set the value to `all`
nav_level: all
